services:
  mastodon-aggregator:
    build: ./mastodon-aggregator/
    depends_on:
      - mosquitto
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - MASTODON_STREAMING_URL=https://techhub.social/api/v1/streaming/public
      - MASTODON_ACCESS_TOKEN=INSERT_ACCESS_TOKEN_HERE
      - PUBSUB_HOST=mosquitto
      - PUBSUB_PORT=1883
      - PUBSUB_CLIENT_ID=mastodon-aggregator
      - PUBSUB_QOS=1
    ports:
      - "8000:8000"
    networks:
      - network
    restart: on-failure

  social-aggregator:
    build: ./social-aggregator/
    depends_on:
      - mosquitto
    environment:
      - HOST=0.0.0.0
      - PORT=8001
    networks:
      - network
    restart: on-failure

  mosquitto:
    image: eclipse-mosquitto:2.0.21
    restart: on-failure
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/logs:/mosquitto/log
      - mosquitto-data:/mosquitto/data
    networks:
      - network

networks:
  network:
    driver: bridge
volumes:
  mosquitto-data:
    driver: local
