services:
  mastodon-aggregator:
    build: ./mastodon-aggregator/
    depends_on:
      - mosquitto
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    networks:
      - network
    restart: on-failure

  mosquitto:
    image: eclipse-mosquitto:2.0.21
    restart: on-failure
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/logs:/mosquitto/log
      - mosquitto-data:/mosquitto/data
    networks:
      - network

networks:
  network:
    driver: bridge
volumes:
  mosquitto-data:
    driver: local
